name: dart_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  auto_injector: ^2.0.4
  result_dart: ^1.1.1
  realm_dart: ^2.0.0
  pub_api_client: ^2.7.0
  uno: ^1.1.9

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
